/*DROPS
DROP TABLE CAMIONEROS CASCADE CONSTRAINTS;
DROP TABLE CAMIONES CASCADE CONSTRAINTS;
DROP TABLE VIAJES CASCADE CONSTRAINTS;
DROP TABLE CARGA CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE VIAJE_CAMIONES_CAMIONEROS CASCADE CONSTRAINTS;
DROP TABLE VIAJE_CARGA_CLIENTES CASCADE CONSTRAINTS;
*/

/*Oracle
/*Create tables*/
CREATE TABLE CAMIONEROS(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(255) DEFAULT NULL,
APELLIDO VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE CAMIONES(
MATRICULA VARCHAR2(7) NOT NULL,
MARCA VARCHAR2(255) DEFAULT NULL,
MODELO VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE VIAJES(
ID NUMBER NOT NULL,
ORIGEN VARCHAR2(255) NOT NULL,
DESTINO VARCHAR2(255)NOT NULL

);

CREATE TABLE CARGA(
ID NUMBER NOT NULL,
PESO NUMBER DEFAULT NULL,
DIMENSIONES VARCHAR2(255) DEFAULT NULL,
VIAJE NUMBER,
TIPO VARCHAR2(255)
);

CREATE TABLE CLIENTES(
CIF VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(255) DEFAULT NULL,
DIRECCION VARCHAR2(255) NOT NULL
);

CREATE TABLE VIAJE_CAMIONES_CAMIONEROS(
CAMIONERO VARCHAR2(9) NOT NULL,
MATRICULA VARCHAR2(7) NOT NULL,
VIAJE NUMBER NOT NULL
);

CREATE TABLE VIAJE_CARGA_CLIENTES(
CARGA NUMBER NOT NULL,
CLIENTE VARCHAR2(9)  NOT NULL,
VIAJE NUMBER NOT NULL,
FECHA DATE DEFAULT NULL,
PRECIO NUMBER NOT NULL,
PAGADO CHAR(2) 
);
/*Constraints PK*/
ALTER TABLE CAMIONEROS ADD CONSTRAINT CAMIONEROS_PK PRIMARY KEY (DNI);
ALTER TABLE CAMIONES ADD CONSTRAINT CAMIONES_PK PRIMARY KEY (MATRICULA);
ALTER TABLE VIAJES ADD CONSTRAINT VIAJES_PK PRIMARY KEY (ID);
ALTER TABLE CARGA ADD CONSTRAINT CARGA_PK PRIMARY KEY (ID);
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY (CIF);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT VIAJE_CAMIONES_CAMIONEROS_PK PRIMARY KEY (VIAJE);
ALTER TABLE VIAJE_CARGA_CLIENTES ADD CONSTRAINT VIAJE_CARGA_CLIENTES_PK PRIMARY KEY (VIAJE);

/*Constraints FK*/

ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT CAMIONEROS_FK FOREIGN KEY (CAMIONERO) REFERENCES CAMIONEROS(DNI);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT CAMIONES_FK FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT VIAJES_CAMIONES_CAMIONEROS_FK FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID);

ALTER TABLE VIAJE_CARGA_CLIENTES ADD CONSTRAINT CARGA_FK FOREIGN KEY (CARGA) REFERENCES CARGA(ID);
ALTER TABLE VIAJE_CARGA_CLIENTES ADD CONSTRAINT CLIENTES_FK FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CIF);
ALTER TABLE VIAJE_CARGA_CLIENTES ADD CONSTRAINT VIAJES_CARGA_CLIENTES_FK FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID);

/*Checks*/
ALTER TABLE VIAJES ADD CONSTRAINT ORIGEN_DESTINO_DIF  CHECK (ORIGEN != DESTINO);
ALTER TABLE VIAJE_CARGA_CLIENTES ADD CONSTRAINT PAGADO_SI_NO  CHECK (PAGADO IN ('SI','NO'));
*/

-- Drops
DROP TABLE IF EXISTS VIAJE_CARGA_CLIENTES;
DROP TABLE IF EXISTS VIAJE_CAMIONES_CAMIONEROS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS CARGA;
DROP TABLE IF EXISTS VIAJES;
DROP TABLE IF EXISTS CAMIONES;
DROP TABLE IF EXISTS CAMIONEROS;

-- Create tables
CREATE TABLE CAMIONEROS(
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    PRIMARY KEY (DNI)
);

CREATE TABLE CAMIONES(
    MATRICULA VARCHAR(7) NOT NULL,
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE VIAJES(
    ID INT NOT NULL,
    ORIGEN VARCHAR(255) NOT NULL,
    DESTINO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CARGA(
    ID INT NOT NULL,
    PESO DECIMAL(10,2),
    DIMENSIONES VARCHAR(255),
    VIAJE INT,
    TIPO VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTES(
    CIF VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(255),
    DIRECCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (CIF)
);

CREATE TABLE VIAJE_CAMIONES_CAMIONEROS(
    CAMIONERO VARCHAR(9) NOT NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    VIAJE INT NOT NULL,
    PRIMARY KEY (VIAJE),
    FOREIGN KEY (CAMIONERO) REFERENCES CAMIONEROS(DNI),
    FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA),
    FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID)
);

CREATE TABLE VIAJE_CARGA_CLIENTES(
    CARGA INT NOT NULL,
    CLIENTE VARCHAR(9) NOT NULL,
    VIAJE INT NOT NULL,
    FECHA DATE,
    PRECIO DECIMAL(10,2) NOT NULL,
    PAGADO ENUM('SI','NO'),
    PRIMARY KEY (VIAJE),
    FOREIGN KEY (CARGA) REFERENCES CARGA(ID),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CIF),
    FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID),
    CHECK (PAGADO IN ('SI','NO'))
);

-- Checks
ALTER TABLE VIAJES ADD CONSTRAINT ORIGEN_DESTINO_DIF CHECK (ORIGEN != DESTINO);
