/* Drops
DROP TABLE IF EXISTS VIAJE_CARGA_CLIENTES;
DROP TABLE IF EXISTS VIAJE_CAMIONES_CAMIONEROS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS CARGA;
DROP TABLE IF EXISTS VIAJES;
DROP TABLE IF EXISTS CAMIONES;
DROP TABLE IF EXISTS CAMIONEROS;
*/

-- Create tables
CREATE TABLE CAMIONEROS(
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    PRIMARY KEY (DNI)
);

CREATE TABLE CAMIONES(
    MATRICULA VARCHAR(7) NOT NULL,
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE VIAJES(
    ID INT NOT NULL AUTO_INCREMENT,
    ORIGEN VARCHAR(255) NOT NULL,
    DESTINO VARCHAR(255) NOT NULL,
    FECHA DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE CARGA(
    ID INT NOT NULL AUTO_INCREMENT,
    PESO DECIMAL(10,2),
    DIMENSIONES VARCHAR(255),
    VIAJE INT,
    TIPO VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTES(
    CIF VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(255),
    DIRECCION VARCHAR(255),
    PRIMARY KEY (CIF)
);

CREATE TABLE VIAJE_CAMIONES_CAMIONEROS(
    CAMIONERO VARCHAR(9) NOT NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    VIAJE INT NOT NULL,
    PRIMARY KEY (VIAJE),
    FOREIGN KEY (CAMIONERO) REFERENCES CAMIONEROS(DNI),
    FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA),
    FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID)
);

CREATE TABLE VIAJE_CARGA_CLIENTES(
    CARGA INT NOT NULL,
    CLIENTE VARCHAR(9) NOT NULL,
    VIAJE INT NOT NULL,
    FECHA DATE,
    PRECIO DECIMAL(10,2) NOT NULL,
    PAGADO ENUM('SI','NO'),
    PRIMARY KEY (VIAJE),
    FOREIGN KEY (CARGA) REFERENCES CARGA(ID),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CIF),
    FOREIGN KEY (VIAJE) REFERENCES VIAJES(ID),
    CHECK (PAGADO IN ('SI','NO'))
);

-- Checks
ALTER TABLE VIAJES ADD CONSTRAINT ORIGEN_DESTINO_DIF CHECK (ORIGEN != DESTINO);
CREATE USER URANZU IDENTIFIED BY 'URANZU';
GRANT ALL PRIVILEGES ON * TO URANZU;
