/*DROPS
DROP TABLE CAMIONEROS CASCADE CONSTRAINTS;
DROP TABLE CAMIONES CASCADE CONSTRAINTS;
DROP TABLE VIAJES CASCADE CONSTRAINTS;
DROP TABLE PAQUETES CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE VIAJE_CAMIONES_CAMIONEROS CASCADE CONSTRAINTS;
*/

/*Create tables*/
CREATE TABLE CAMIONEROS(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(255) DEFAULT NULL,
APELLIDO VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE CAMIONES(
MATRICULA VARCHAR2(7) NOT NULL,
MARCA VARCHAR2(255) DEFAULT NULL,
MODELO VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE VIAJES(
ID NUMBER NOT NULL,
ORIGEN VARCHAR2(255) NOT NULL,
DESTINO VARCHAR2(255)NOT NULL,
FECHA DATE DEFAULT NULL
);

CREATE TABLE PAQUETES(
ID NUMBER NOT NULL,
REMITENTE VARCHAR2(9) NOT NULL,
DESTINATARIO VARCHAR2(9) NOT NULL,
PESO NUMBER DEFAULT NULL,
DIMENSIONES VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE CLIENTES(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(255) DEFAULT NULL,
APELLIDO VARCHAR2(255) DEFAULT NULL,
DIRECCION VARCHAR2(255) NOT NULL
);

CREATE TABLE VIAJE_CAMIONES_CAMIONEROS(
DNI VARCHAR2(9) NOT NULL,
MATRICULA VARCHAR2(7) NOT NULL,
ID NUMBER NOT NULL
);

/*Constraints PK*/
ALTER TABLE CAMIONEROS ADD CONSTRAINT CAMIONEROS_PK PRIMARY KEY (DNI);
ALTER TABLE CAMIONES ADD CONSTRAINT CAMIONES_PK PRIMARY KEY (MATRICULA);
ALTER TABLE VIAJES ADD CONSTRAINT VIAJES_PK PRIMARY KEY (ID);
ALTER TABLE PAQUETES ADD CONSTRAINT PAQUETES_PK PRIMARY KEY (ID);
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY (DNI);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT VIAJE_CAMIONES_CAMIONEROS_PK PRIMARY KEY (DNI,MATRICULA,ID);

/*Constraints FK*/
ALTER TABLE PAQUETES ADD CONSTRAINT PAQUETES_REMITENTE FOREIGN KEY (REMITENTE) REFERENCES CLIENTES(DNI);
ALTER TABLE PAQUETES ADD CONSTRAINT PAQUETES_DESTINATARIO FOREIGN KEY (DESTINATARIO) REFERENCES CLIENTES(DNI);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT CAMIONEROS_FK FOREIGN KEY (DNI) REFERENCES CAMIONEROS(DNI);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT CAMIONES_FK FOREIGN KEY (MATRICULA) REFERENCES CAMIONES(MATRICULA);
ALTER TABLE VIAJE_CAMIONES_CAMIONEROS ADD CONSTRAINT VIAJES_FK FOREIGN KEY (ID) REFERENCES VIAJES(ID);

/*Checks*/
