/* DROPS
DROP SEQUENCE id_viaje_autoincrementable;
DROP SEQUENCE id_carga_autoincrementable;
DROP PROCEDURE insert_Camionero;
DROP PROCEDURE DELETE_CAMIONERO;
DROP PROCEDURE UPDATE_CAMIONERO;
DROP PROCEDURE insert_Camion;
DROP PROCEDURE DELETE_CAMION;
DROP PROCEDURE UPDATE_CAMION;
DROP PROCEDURE INSERT_VIAJE;

*/

CREATE SEQUENCE id_viaje_autoincrementable
INCREMENT BY 1
START WITH 1
NOCYCLE;

CREATE SEQUENCE id_carga_autoincrementable
INCREMENT BY 1
START WITH 1
NOCYCLE;

/*Procedures Camioneros*/
CREATE OR REPLACE PROCEDURE INSERT_CAMIONERO (DNI VARCHAR2,NOMBRE VARCHAR2,APELLIDO VARCHAR2) AS 
    BEGIN
        INSERT INTO CAMIONEROS (DNI,NOMBRE,APELLIDO)
        VALUES (INSERT_CAMIONERO .DNI,INSERT_CAMIONERO .NOMBRE,INSERT_CAMIONERO .APELLIDO);
    END;
/

CREATE OR REPLACE PROCEDURE DELETE_CAMIONERO(DNI VARCHAR2) AS
    BEGIN
       DELETE FROM CAMIONEROS WHERE DNI=DELETE_CAMIONERO.DNI;
    END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CAMIONERO(DNI VARCHAR2,NOMBRE VARCHAR2,APELLIDO VARCHAR2) AS 
    BEGIN
        UPDATE CAMIONEROS
        SET NOMBRE=UPDATE_CAMIONERO.NOMBRE, APELLIDO=UPDATE_CAMIONERO.APELLIDO
        WHERE DNI=UPDATE_CAMIONERO.DNI;
    END;
/

/*Procedures camiones*/
CREATE OR REPLACE PROCEDURE INSERT_CAMION (MATRICULA VARCHAR2,MARCA VARCHAR2,MODELO VARCHAR2) AS 
    BEGIN
        INSERT INTO CAMIONES (MATRICULA,MARCA,MODELO)
        VALUES (INSERT_CAMION.MATRICULA,INSERT_CAMION.MARCA,INSERT_CAMION.MODELO);
    END;
/

CREATE OR REPLACE PROCEDURE DELETE_CAMION(MATRICULA VARCHAR2) AS
    BEGIN
       DELETE FROM CAMIONES WHERE MATRICULA=DELETE_CAMION.MATRICULA;
    END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CAMION(MATRICULA VARCHAR2,MARCA VARCHAR2,MODELO VARCHAR2) AS 
    BEGIN
        UPDATE CAMIONES
        SET MARCA=UPDATE_CAMION.MARCA, MODELO=UPDATE_CAMION.MODELO
        WHERE MATRICULA=UPDATE_CAMION.MATRICULA;
    END;
/

/*PROCEDURES VIAJE*/
CREATE OR REPLACE PROCEDURE INSERT_VIAJE (ORIGEN VARCHAR2,DESTINO VARCHAR2) AS 
    BEGIN
        INSERT INTO VIAJES (ID,ORIGEN,DESTINO)
        VALUES (id_viaje_autoincrementable.NEXTVAL,INSERT_VIAJE.ORIGEN,INSERT_VIAJE.DESTINO);
    END;
/

CREATE OR REPLACE PROCEDURE DELETE_VIAJE(ID NUMBER) AS
    BEGIN
       DELETE FROM VIAJES WHERE ID=DELETE_VIAJE.ID;
    END;
/

CREATE OR REPLACE PROCEDURE UPDATE_VIAJE(ID NUMBER,ORIGEN VARCHAR2,DESTINO VARCHAR2) AS 
    BEGIN
        UPDATE VIAJES
        SET ORIGEN=UPDATE_VIAJE.ORIGEN, DESTINO=UPDATE_VIAJE.DESTINO
        WHERE ID=UPDATE_VIAJE.ID;
    END;
/
EXECUTE INSERT_VIAJE ('COSLADA','MIRANDA DE EBRO');
SELECT * FROM VIAJES;
EXECUTE UPDATE_VIAJE(3,'MIRANDA DE EBRO','USURBIL');
EXECUTE DELETE_VIAJE(3);
/*PROCEDURES CARGA*/
CREATE OR REPLACE PROCEDURE INSERT_CARGA (PESO NUMBER,DIMENSIONES VARCHAR2,VIAJE NUMBER,TIPO VARCHAR2) AS 
    BEGIN
        INSERT INTO CAMIONES (MATRICULA,MARCA,MODELO)
        VALUES (INSERT_CAMION.MATRICULA,INSERT_CAMION.MARCA,INSERT_CAMION.MODELO);
    END;
/
CREATE TABLE CARGA(
ID NUMBER NOT NULL,
PESO NUMBER DEFAULT NULL,
DIMENSIONES VARCHAR2(255) DEFAULT NULL,
VIAJE NUMBER,
TIPO VARCHAR2(255)
);




EXECUTE INSERT_Camionero ('PRUEBA','PRUEBA','PRUEBA');
SELECT * FROM camioneros WHERE dni='PRUEBA';
EXECUTE UPDATE_CAMIONERO('PRUEBA','MODIFICADO','MODIFICADO');
EXECUTE DELETE_CAMIONERO('PRUEBA');


