/* DROPS
DROP SEQUENCE id_viaje_autoincrementable;
DROP SEQUENCE id_carga_autoincrementable;
DROP PROCEDURE insert_Camionero;
DROP PROCEDURE DELETE_CAMIONERO;
DROP PROCEDURE UPDATE_CAMIONERO;
DROP PROCEDURE insert_Camion;
DROP PROCEDURE DELETE_CAMION;
DROP PROCEDURE UPDATE_CAMION;
*/

CREATE SEQUENCE id_viaje_autoincrementable
INCREMENT BY 1
START WITH 1
NOCYCLE;

CREATE SEQUENCE id_carga_autoincrementable
INCREMENT BY 1
START WITH 1
NOCYCLE;

/*Procedures Camioneros*/
CREATE OR REPLACE PROCEDURE INSERT_CAMIONERO (DNI VARCHAR2,NOMBRE VARCHAR2,APELLIDO VARCHAR2) AS 
    BEGIN
        INSERT INTO CAMIONEROS (DNI,NOMBRE,APELLIDO)
        VALUES (INSERT_CAMIONERO .DNI,INSERT_CAMIONERO .NOMBRE,INSERT_CAMIONERO .APELLIDO);
    END;
/

CREATE OR REPLACE PROCEDURE DELETE_CAMIONERO(DNI VARCHAR2) AS
    BEGIN
       DELETE FROM CAMIONEROS WHERE DNI=DELETE_CAMIONERO.DNI;
    END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CAMIONERO(DNI VARCHAR2,NOMBRE VARCHAR2,APELLIDO VARCHAR2) AS 
    BEGIN
        UPDATE CAMIONEROS
        SET NOMBRE=UPDATE_CAMIONERO.NOMBRE, APELLIDO=UPDATE_CAMIONERO.APELLIDO
        WHERE DNI=UPDATE_CAMIONERO.DNI;
    END;
/

/*Procedures camiones*/
CREATE OR REPLACE PROCEDURE INSERT_CAMION (MATRICULA VARCHAR2,MARCA VARCHAR2,MODELO VARCHAR2) AS 
    BEGIN
        INSERT INTO CAMIONES (MATRICULA,MARCA,MODELO)
        VALUES (INSERT_CAMION.MATRICULA,INSERT_CAMION.MARCA,INSERT_CAMION.MODELO);
    END;
/

CREATE OR REPLACE PROCEDURE DELETE_CAMION(MATRICULA VARCHAR2) AS
    BEGIN
       DELETE FROM CAMIONES WHERE MATRICULA=DELETE_CAMION.MATRICULA;
    END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CAMION(MATRICULA VARCHAR2,MARCA VARCHAR2,MODELO VARCHAR2) AS 
    BEGIN
        UPDATE CAMIONES
        SET MARCA=UPDATE_CAMION.MARCA, MODELO=UPDATE_CAMION.MODELO
        WHERE MATRICULA=UPDATE_CAMION.MATRICULA;
    END;
/

/*PROCEDURES CARGA*/

EXECUTE INSERT_CAMION ('PRUEBA','PRUEBA','PRUEBA');
SELECT * FROM CAMIONES WHERE MATRICULA='PRUEBA';
EXECUTE UPDATE_CAMION('PRUEBA','MODIFICADO','MODIFICADO');
EXECUTE DELETE_CAMION('PRUEBA');


